### ISSUE TITLE
Allow for install of packages using rpm-ostree

### ISSUE THREAD

**Issue by BeeGrech** [teemtee/tmt#1095]
To support ostree images, it would be helpful for "preparation" and or "required" to support rpm-ostree install from within the fmf file.

ie: (see how entry)
 prepare:
   how: rpm-ostree-install
   package:
       - tmp/RPMS/noarch/tmt-0.15-1.fc31.noarch.rpm
       - tmp/RPMS/noarch/python3-tmt-0.15-1.fc31.noarch.rpm

Of course this may get tricky if packages are already installed, also in general to apply the overlay a reboot occurs, however in some cases, by supplying the -A, --apply-live argument, this can be avoided

I think its worth a discussion though

**Comment by FrNecas** [comment]
Do I understand correctly that the use-case for this is provisioning with for example Fedora Silverblue image (e.g. with how: virtual) and then installing stuff in there? I think this should be doable without a lot of problems by implementing a new plugin. We already have `Guest.reboot()` which will take care of the rebooting so if the provision method supports it, we can install the packages and reboot. Otherwise (e.g. provision -h local) we can try using `-A`.

**Comment by psss** [comment]
I see three options how to approach this:

* A new `prepare` plugin, e.g. `prepare --how rpm-ostree-install` as suggested above
* Extending the existing `install` plugin with `rpm-ostree` which could reuse some of the code
* Cover this in the newly planned "almighty" install plugin which should support installing from brew/koji and much more

**Comment by BeeGrech** [comment]
In my use case - We are testing Centos-Stream-9 ostree deployment
- The issue with installing packages on ostree images, is the RO OS 

Another issue I would consider is I can see this applying to both plan and test fmf files

**Comment by BeeGrech** [comment]
Just thinking about this further, in order to support multiple deployments, an implementation where this is provided in the command line or detected by TMT runner globally would be better. Because providing hard-coded in a plan file or test file I think would add complexity to the fmf files

**Comment by BeeGrech** [comment]
also consider soft dependency case, where currently rpm-ostree reports an error when no package match is found

**Comment by BeeGrech** [comment]
@psss Has any decision been made of the 3. I could offer support to work on this issue.

**Comment by BeeGrech** [comment]
One concern, rpm ostree does not represent the same args, or behavior like dnf to yum.

**Comment by schrht** [comment]
ack+1 to this issue.

**Comment by psss** [comment]
> Just thinking about this further, in order to support multiple deployments, an implementation where this is provided in the command line or detected by TMT runner globally would be better.

So if I understand it correctly the `prepare --how rpm-ostree-install` approach which would use a special dedicated plugin for the installation is not a good option as it would be closely tied with the `rpm-ostree` use case. The almighty install plugin will take some time, so the best candidate for a short-term solution would/could be to adjust the current `install` plugin.

> @psss It appears its currently a [try except](https://github.com/teemtee/tmt/blob/b6c733905d172f9b77399bb4154645e589f1b112/tmt/steps/prepare/install.py#L165) clause in the prepare step?
> then step execute still calls the prepare? in the case of requires provided with the test.fmf

The `install` prepare plugin is used for both installing packages specified in the [plan](https://tmt.readthedocs.io/en/latest/spec/plans.html#install) and in the [require](https://tmt.readthedocs.io/en/latest/spec/tests.html#require) and [recommend](https://tmt.readthedocs.io/en/latest/spec/tests.html#recommend) attribute. So adding support to it would cover both use cases. The `recommend` one would probably have to be handled in a special way.

All in all I think it would be ok to make adjustments of the `install` plugin to use the `rpm-ostree install --apply-live` command when desired. @BeeGrech, is there a check which could be performed at the beginning of the `go()` method to reliable assess/decide that `rpm-ostree` should be used instead of `dnf` or `yum`?

**Comment by BeeGrech** [comment]
@psss I agree, recommend needs to be handled a special way. Actually I don't really like the options, but basically in my other work, in the case of 'soft dependencies' I am only ignoring the exit status because rpm-ostree does not have a --skip-broken equivalent.

otherwise for detection I was checking for the existence of the rpm-ostree binary under /usr/bin -- haven't seen any issues back testing this against other standard releases ... yet

**Comment by lukaszachy** [comment]
@BeeGrech How rpm-ostree behaves when you ask to install more packages and only few of them are available? Is it all or nothing? If yes we might want to do the install in loop so those packages which are available are installed.

**Comment by BeeGrech** [comment]
@lukaszachy If a request is made with a package that no match is found, the entire operation is aborted with error.  Currently we are using a couple of different parameters to preempt the condition in which we have packages already installed:
Default action will exit with an error and description EX: "error: "PACKAGE" is already provided by ...
--allow-inactive Allow inactive package requests
--idempotent  Do nothing if package already (un)installed

However as i mentioned there is no --skip-broken, in the case of no match rpm-ostree exits with "error: Packages not found: PACKAGENAME

Setting a loop, with a large number of packages could take some time but might be the best option. The reason it takes  some time is because of the overlay action and live apply on top of the active commit. (and im sure there is a much more technical explanation available from the coreos team) 

on the topic of --skip-broken I've opened an issue with coreos/rpm-ostree, however the team is resistant to wanting to implement the feature.

**Comment by psss** [comment]
> Setting a loop, with a large number of packages could take some time but might be the best option.

Yeah, so this looks like the best available option. Even if it is slow, I'd say better than nothing.

**Comment by BeeGrech** [comment]
PR for this issue:
https://github.com/teemtee/tmt/pull/1164
