### ISSUE TITLE
convert failed for package of Makefile with minus as the first sign.

### ISSUE THREAD

**Issue by psklenar** [teemtee/tmt#1165]
Makefile contains MINUS PACKAGE
./Install/bind97-installer/Makefile:	@echo "Requires:        -bind-libs -bind-utils -bind" >> $(METADATA)

then its' converted as:
- -bind-libs
- -bind-utils
- -bind
 
WHEN RUN:
stderr (2/2 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rpm: -bind-libs: unknown option
Command line error: argument -b/--best: ignored explicit argument 'ind-libs'

-------------
There are these -package as beaker feature to uninstall them. tmt convert it wrongly

**Comment by lukaszachy** [comment]
Any link to documentation what `-package` was supposed to do?

**Comment by lukaszachy** [comment]
Thank you, so we have two problems:
1. no test attribute to specify that package has to be removed
2. processing in tmt import

@psss  I guess import should fail? or Only warn but provide incomplete conversion?

**Comment by psklenar** [comment]
> @psss I guess import should fail? or Only warn but provide incomplete conversion?
or provide incomplete conversion + warn + add attribute **adjust : - enabled: false** in fmf of test

**Comment by psss** [comment]
I would say this special `Requires` syntax should give a fail during `tmt test import`: This is unexpected and uninstalling packages is currently not supported in `tmt` so that test might not work at all. Failing with a non-zero exit code should give the user a clear sign that something is wrong and has to be inspected.

@psklenar, if I understand it correctly, so you suggest that any test requiring package uninstallation should be automatically disabled? I'm afraid that doing that together with mass conversion of tests could lead to users overlooking possible problems. @hegerj, what are your thoughts on this?

**Comment by hegerj** [comment]
I think the `import` should fail with some sort of warning but the test should not be disabled. It is far too risky. Failing test will alert a tester that there is a problem that must be dealt with. Disabled test may disappear forever.

**Comment by lukaszachy** [comment]
I'll go with "Failing with a non-zero exit code should give the user a clear sign that something is wrong and has to be inspected."
together with reasonable message among lines of "uninstalling packages is not supported by tmt so automated conversion is not possible - you need to manually fix Requires"

We can't produce 'enabled' test with invalid metadata - If user runs conversion script for each test this could go unnoticed and there is high risk of either broken whole testsuite (painful debugging to find culprit) or masking issue if additional package is present.
