### ISSUE TITLE
'tmt clean' usage unclear

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#1176]
```
$ tmt clean --help
Usage: tmt clean [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
```

So I try 2 commands (don't want to clean images):

```
$ tmt clean runs guests
clean
Path 'guests' doesn't exist.
```

This is unexpected. The workaround:

```
$ tmt clean runs ; tmt clean guests
clean
    runs
clean
    guests
```

**Comment by FrNecas** [comment]
The problem is that `tmt clean runs` takes a positional argument (`[PATH]`) to specify where to look for the runs. With chaining, click considers `guest` to be this path which causes this weird behaviour. Just FYI: doing `tmt clean runs guests` does not make much sense, the run workdirs will be deleted and there will be no more guests to clean.

However, I remember that we discussed this during the implementation of the clean command and the consensus was to remove chaining (see comments after https://github.com/teemtee/tmt/pull/646#issuecomment-816612907 ) so this may be an oversight/something getting lost in a rebase. I will remove the possibility of chaining so that the help message is not confusing and it's apparent that one has to do `tmt clean guests && tmt clean runs`

**Comment by FrNecas** [comment]
^^ Disregard that :) We agreed on supporting chaining, I will update the PR, `tmt clean guests runs` should hopefully work in the upcoming release
