### ISSUE TITLE
Create JSON schema for TMT

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1188]
We need to create a JSON schema for TMT.

Schema validation should happen before loading the data to `tmt`.

Work items:
- [x] decide on basic structure of schema validation
- [x] create json schema for tests
- [x] create json schema for plans
- [x] create json schema for stories
- [x] add tests and connect to CI

Related to #602

**Comment by happz** [comment]
Note that it should be possible to create partial schemas, for different levels, since `base.Core` subclasses like `Test` and `Plan` "own" just part of the structure. With references, it should be possible to have a fairly nice schema Soon (TM), e.g. for test attributes only.

(I can imagine `base.Core` subclasses loading schema from a file, based on `self.__class__.__name__`, making it again a transparent action).

**Comment by psss** [comment]
So I guess, this part (json schemas) has been completed?

**Comment by happz** [comment]
I agree - there are leftovers (e.g. #1395), but "create schemas" is definitely done. Now "use schemas", that's still open :)
