### ISSUE TITLE
Disable `test --name` filter in the `upgrade` plugin discover

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1208]
The fresh implementation of the `upgrade` execute plugin in #1196 does not support filtering tests using the `test --name` filter. Here's a short real life example from the `tmt` repo:

    tmt run -av plan -n core test -n smoke execute -h upgrade -u https://github.com/teemtee/upgrade/ -t prepare

The `test -n` filter is applied to the upgrade tasks as well. We need to find a way how to disable the global cli test filter for upgrade tasks which is implemented here:

https://github.com/teemtee/tmt/blob/7b73789624b27c88e8fcc318940fd45cf4ac1f5d/tmt/base.py#L1329

**Comment by FrNecas** [comment]
We initially thought that passing some option to DiscoverFmf.go() and some ifs would be enough but that is not very systematic. I think we need to modify `Test._opt` such that if some true flag on `Test` is set, it returns the default value (None or empty list) rather than the actual value. Any other similar approach?
