### ISSUE TITLE
Make reconnection timeout after reboot configurable

### ISSUE THREAD

**Issue by FrNecas** [teemtee/tmt#1214]
There are multiple scenarios where reboot is used, each requires a slightly different timeout handling. For a regular reboot during test, the machine should come back up in a matter of seconds (or at worst minutes). However, for cases such as upgrade testing (see #1196), the reboot may take even up to an hour. As a workaround, #1210 extended this timeout, but this is not great since upgrades are quite specific.

The current proposal is to extend the `tmt-reboot` command with a `-t` option which would allow the running test to specify how long the reboot may take depending on the scenario. This information could be stored in the reboot request file, along with the custom command (`-c`), e.g. in a JSON.

During implementation, do not forget about the internal plugins! (the API of the `reboot` method will most-likely need a new argument, `timeout` so it needs to be adjusted in all provision plugins).

**Comment by pcahyna** [comment]
This is needed also for system recovery testing (ReaR), since the recovery process is invisible for tmt (at least in our current implementation) and looks like a very long reboot.
An additional option for tmt-reboot is probably the best solution, because it allows using different reboot timeouts in the same test (depending on the place where the reboot is initiated). It is probably more difficult to implement than storing it in test metadata, though.
