### ISSUE TITLE
system didn't reboot as expected

### ISSUE THREAD

**Issue by qqfang97** [teemtee/tmt#1225]
We have some testcases need reboot, we use file based reboot control. but rhts-reboot didn't immediately reboot.
script like:
#!/bin/sh
tmpfile=/mnt/testarea/reboot
if [ ! -e $tmpfile ]; then
    touch $tmpfile
    rhts-reboot
else
    echo 'After the reboot'
fi
rm -rf $tmpfile

But tmt will continue remove file. Then reboot loop forever.

**Comment by FrNecas** [comment]
Thanks for the report, this should be solved by #1213 (which will be included in the 1.14 release) . The problem was that our `rhts-reboot` implementation did not kill the running test. Just to make sure that this fixes your problem, could you try running the latest tmt? The instructions for running latest tmt in a venv are here: https://tmt.readthedocs.io/en/stable/contribute.html#develop (or you may as well use the copr build made by packit on the mentioned PR). Let us know if this fixed your problem

**Comment by FrNecas** [comment]
For reference, these are the latest copr builds: https://github.com/teemtee/tmt/runs/6690357229

**Comment by qqfang97** [comment]
Thanks, the latest copr build works fine.

**Comment by FrNecas** [comment]
Thanks for the confirmation, I am closing this issue, the fix will be present in 1.14 (which should be released soon)
