### ISSUE TITLE
tmt-reboot: Add efibootmgr configuration and option to disable it

### ISSUE THREAD

**Issue by juk** [teemtee/tmt#1382]
Some UEFI systems that has efibootmgr installed need BootNext to be set BootCurrent before reboot.
efibootmgr configuration could be a default step in tmt-reboot and provide a full compatibility with rstrnt-reboot

But sometime, for example for kexec testing, a soft reboot is necessary.

An updated tmt-reboot could provide both reboot options:
* Configure efibootmgr before reboot by default
* Option to disable efibootmgr configuration when necessary

[1] https://restraint.readthedocs.io/en/latest/commands.html#rstrnt-prepare-reboot
     https://github.com/restraint-harness/restraint/blob/master/scripts/rstrnt-prepare-reboot

**Comment by thrix** [comment]
Seems this is a priority for the Kernel team, let's try to find somebody who could implement it. Testing Farm team can provide an UEFI enabled machine if that would help with testing (or a Beaker machine can be used)

**Comment by psss** [comment]
@juk suggested that as for now it's not necessary to add a new script `rstrnt-prepare-reboot`. The functionality could be added directly to `tmt-reboot` (and its aliases) with option which would disable the `efibootmgr` adjustments. @pfdaly, would you be interested in implemeting this?

**Comment by pfdaly** [comment]
I'll give it a quick read through now with the intention to start implementing something on Monday.

**Comment by pcahyna** [comment]
Note that the current implementation of the functionality in Restraint scripts is harmful: https://github.com/restraint-harness/restraint/pull/260

**Comment by psss** [comment]
Thanks for sharing the link! From the discussion in the above-mentioned issue, @pcahyna, @juk, do you have any specific recommendation about the way how we should approach it in `tmt` implementation?

**Comment by emmawu** [comment]
Hi, I am from kernel QE team and my team is responsible for testing kdump/crash related functionalities. Thanks @juk raising the request for tmt-reboot enhancement. This is what we need in kexec test.

I am kinds of lost in the discussion of [rstrnt-prepare-reboot](https://restraint.readthedocs.io/en/latest/commands.html?highlight=rstrnt-prepare-reboot#rstrnt-prepare-reboot) and [rstrnt-reboot](https://restraint.readthedocs.io/en/latest/commands.html?highlight=rstrnt-reboot#rstrnt-reboot) in https://github.com/restraint-harness/restraint/pull/260. It seems the issue reporter tried to fix is the timeout of efibootmgr - to make sure efibootmgr nextboot configure doesn't expirer before system fully shut down and reboot. I guess it doesn't conflict with this ticket no matter https://github.com/restraint-harness/restraint/pull/260 is implemented or not.

`restrnt-reboot` performs a regular boot. Due to Beaker constraints on UEFI system, in order to perform a regular boot, the efibootmgr Nextboot option must be set to a disk boot (the value taken from current boot), otherwise the next boot is always a network boot which would cause the Beaker UEFI system to re-install from a PXE boot - it will break a Beaker test unexpectedly. The setting of efibootmgr nextboot is always a part of `restrnt-reboot` command. What `rstrnt-prepare-reboot` does is to abstract the efibootmrg -n implementation to a separate function/script. So the user could choose either
- to run `rstrnt-prepare-reboot` independently to set efi next boot for preparing a panic test, 
- or to run `restrnt-reboot` which always call `rstrnt-prepare-reboot` so Beaker UEFI system could perform a regular boot instead of going to pxe boot installation unexpectedly.

The request in this issue for a third scenario: **kexec boot**. 

kexec boot is a regular `reboot` command called after `kexec -l` command (This is not a panic test). It will kexec boot to another kernel without going through the regular bios boot process. So if 'restrnt-reboot' is called and efi nextboot set to disk, it will not take affect in the kexec boot, but in the task/jobs run after the kexec boot test. So for kexec boot test, we will run "reboot" (not `restrnt-reboot`) explicitly to make sure a kexec boot is performed without interrupting any job/tasks run afterwards on the system. 

When it comes to running kexec/panic tests in tmt environement. tmt guide says rstrnt-reboot is backward compatible in tmt (i.e. rstrnt-reboot = tmt-reboot). So we hope tmt could provide

- rstrnt-reboot/tmt-reboot exactly same in restraint or in tmt environment - That is, efibootmgr nextboot is configured to allow Beaker UEFI system to perform a regular boot.
- `rstrnt-reboot` support an option to leave efibootmgr nextboot as it is. Currently `kexec -l xxx && reboot` doesn't work in tmt, it would lost connection to the test machine.

**Comment by juk** [comment]
@psss as @emmawu mentioned https://github.com/restraint-harness/restraint/pull/260 is not a concern at the moment.
If necessary it could be address later once enhancement to configure efibootmgr nextboot is in-place.

**Comment by thrix** [comment]
@pfdaly hi, so are you working on this?

**Comment by thrix** [comment]
@pfdaly promised to resume work on this soon.

thanks for clarification @juk and @emmawu

**Comment by juk** [comment]
@emmawu Could you please review https://github.com/teemtee/tmt/pull/1506/commits/4e40d0e94cc6d1f97081f9200f65353df291fc07#diff-a9d33e5ac8c84b8e638d87df49f589692e4271162fc04fc5bbd45b93b2d8d55aR29

Noticed that "efi" option is disabled by default. @emmawu would it work for you? 
So to configure nextboot you would need to enable "efi" option each time you do tmt-reboot.

**Comment by emmawu** [comment]
@juk,  Thanks. The change looks good to me. Then with this change, running tmt-reboot with option '-e', it will not update the efi BootNext.

**Comment by pcahyna** [comment]
> It seems the issue reporter tried to fix is the timeout of efibootmgr - to make sure efibootmgr nextboot configure doesn't expirer before system fully shut down and reboot. I guess it doesn't conflict with this ticket (...)

No, it does not conflict with this ticket, but it would be good to not reintroduce the same problem.
