### ISSUE TITLE
Race condition when creating last-run symlink

### ISSUE THREAD

**Issue by mizdebsk** [teemtee/tmt#1466]
I am concurrently running tmt multiple times in parallel, passing full path as run ID:
`tmt run --id /full/path ...`

This works in general. However from time to time I am getting the following error:

```
Unable to save last run '/home/kojan/.config/tmt'.
[Errno 17] File exists: '/tmp/apache-commons-io-b3-validate-681338467230517662/tmt' -> '/home/kojan/.config/tmt/last-run'
```

This looks like a race condition in `tmt.utils.Config.last_run()`. It first tries to remove last-run symlink, then create it. But in between, another process can create the symlink. This leads to the crash.

**Comment by lukaszachy** [comment]
@psss How much do we care about _correct_ last-run for parallel runs? 
Doing symlink in atomic way will be [difficult](https://stackoverflow.com/questions/8299386/modifying-a-symlink-in-python/55742015#55742015) and at same time useless.

If user runs multiple tmt commands in parallel then using --last isn't good thing to do (#525).

I'd just change code to not break when symlink exists.

Note that parallel runs are buggy also because of #659.

**Comment by mizdebsk** [comment]
Thanks for fixing this so quickly!
