### ISSUE TITLE
User defined filters for system configurations

### ISSUE THREAD

**Issue by juk** [teemtee/tmt#1601]
That would be helpful to have a feature that allows user to define their own system requirements. 
For example, I regularly need to test on system with various HW configurations and would like to define my own configurations and reuse them.

AMD__ROME:
CPU family=23
CPU model=49

MEMORY_MIN_64G
SYSTEM memory >= 64G

NOGSS 
SYSTEM name != "%gss%"

**Comment by bmeneg** [comment]
Am I right to assume that this requirement has been _partially_ fulfilled with https://tmt.readthedocs.io/en/stable/plugins/provision.html#hardware-requirement-support ?

**Comment by happz** [comment]
I believe so, yes. This can be closed then.

**Comment by bmeneg** [comment]
@happz I probably jumped ahead and missed the real meaning of this feature request: the idea is to have a way to set separated names or filters for the provision step, so instead of requiring every single hw requirement on every plan, it would be possible to request the "tag name".

Can we reopen it?

**Comment by bmeneg** [comment]
I've opened https://github.com/teemtee/tmt/issues/3447 as follow up.
