### ISSUE TITLE
tmt tests import Beaker Makefile metadata "Requires" fields to "require" instead of "recommend" in the main.fmf

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#1665]
When I import my beaker test into tmt format,  the packages defined in beaker Makefile metadata "Requires" field are exported into main.fmf as "recommend" packages. Is it reasonable to make them into 'require' pkgs? Per my understanding these are the required pkgs, without these packages, the tests can not be run. 

Beaker Makefile metadata:
@echo "Requires:     package_1 package_2 " >> $(METADATA)

**After run $ tmt tests import --no-nitrate --type all**

**Actual result:**
In main.fmf
recommend:
  - package_1
  - package_2

**Expected result:**
In main.fmf
require:
  - package_1
  - package_2
since they are _MUST_ required packages.

**Comment by psss** [comment]
This is intentional as `Requires` in `Makefile` is transformed by Beaker into kickstart packages which are installed with `--skip-broken` so that any missing package is ignored. The `RhtsRequires` metadata from `Makefile` are converted during `make rpm` to rpm requires, which is the "hard require", so this field is converted to tmt `require` key. Does that make sense?

**Comment by guoguojenna** [comment]
> This is intentional as `Requires` in `Makefile` is transformed by Beaker into kickstart packages which are installed with `--skip-broken` so that any missing package is ignored and thus we convert it into `recommend`.
> 
> The `RhtsRequires` metadata from `Makefile` are converted during `make rpm` to rpm requires, which is the "hard require", so this field is converted to tmt `require` key. Does that make sense?

Make sense for me now, thanks!
