### ISSUE TITLE
Allow modification of imported plans

### ISSUE THREAD

**Issue by mkoncek** [teemtee/tmt#1788]
I have a use case for the unimplemented feature mentioned in https://tmt.readthedocs.io/en/latest/spec/plans.html#import-plans.
Context: we maintain 100 java packages, using a custom test framework which is run from podman. We can use this in a more constrained version on all Fedora Java packages to test simple regressions or dangling symlinks in the packages... For the maintainers it should be no more complex than adding a file like this: https://src.fedoraproject.org/rpms/lucene/c/a77617ce4eb4a768b56e6c31be3276691f2b2513?branch=rawhide

Previously we used remote test feature to avoid any copy-pasting that is not necessary. Later I wanted to change that into importing remote plans: https://src.fedoraproject.org/rpms/lucene/pull-request/11#request_diff. This works for simple cases, but will not work in case like the `maven` package: https://src.fedoraproject.org/rpms/maven/blob/f3b53e28f5bd1716080250c1a1cda34a93220b18/f/plans/javapackages.fmf (maven builds 3 mutually conflicting subpackages)

**Comment by psss** [comment]
Thanks for sharing the use case. Modifying imported remote plans should be technically possible, though I expect there will be some interesting stuff to be resolved in order to merge content of the fetched `fmf.Tree` with the local one. Perhaps we will need to implement something like `fmf.Tree.merge_other()` or something like that first in the `fmf` code base. Ideas and patches are welcome!

**Comment by lukaszachy** [comment]
What value should win? Should it be customisable?  I can imagine users will be able to utilize both.
