### ISSUE TITLE
A confusing `guestname` in the `mrack` provision output

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1946]
It seems that Beaker job id is printed as `guestname` in the terminal output:

```
/plans/default
    provision
        how: beaker
        order: 50
        guest: has been requested
        guestname: 7672489
        status: Processed
...
```

@Tiboris, should it be `job id` ? Or did you want to show guest name instead?

**Comment by happz** [comment]
`guestname` is not generally used in tmt lingo. The only other plugin that uses it is `artemis`, but that's expected because `guestname` is an important part of Artemis API, similar to Beaker job ID or OpenStack instance ID. If you wish to display the "guest name", `name` would be better - although I believe superclass would display it already if it wouldn't be `default-0`, I suppose you don't need to do anything to get the name shown. Note that the "guest name" does *not* changing during tmt run, it's assigned once and for all. What's changing is the guest *address*, or hostname if you wish, i.e. no `guestname` either.

For the Beaker job ID, `job id` sounds appropriate.

**Comment by Tiboris** [comment]
Thanks @happz

**Comment by psss** [comment]
Yeah, her `job id` sounds good to identify the beaker job. I would not recommend using `name` as it is the unique guest identifier handled by `tmt`. If we're going to show the hostname of the reserved box, let's call it `hostname`?
