### ISSUE TITLE
Variables with spaces need to be escaped

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1964]
I encountered this when doing some sanity testing, it is weird.

We have a simple sanity test for running various commands on the host:

https://gitlab.com/testing-farm/tests/-/blob/main/testing-farm/script/test.sh

```
❯ git clone http://gitlab.com/testing-farm/tests
❯ cd tests

❯ tmt run -e SECRET=some-secret -e SCRIPT='test $SECRET = some-secret' plan --name /testing-farm/sanity
/var/tmp/tmt/run-039
Invalid variable specification '$SECRET'.

❯ tmt run -e SECRET=some-secret -e SCRIPT='test\ $SECRET\ =\ some-secret' plan --name /testing-farm/sanity
/var/tmp/tmt/run-040

/testing-farm/sanity
    discover
        how: fmf
        directory: /home/mvadkert/git/gitlab.com/testing-farm/tests
        tests: /testing-farm/script
        summary: 1 test selected
    provision
        how: container
        image: fedora:latest
        distro: Fedora Linux 37 (Container Image)
        summary: 1 guest provisioned
    prepare
        summary: 0 preparations applied
    execute
        how: tmt
        summary: 1 test executed            
    report
        how: display
        summary: 1 test passed
    finish
        container: stopped
        container: removed
        summary: 0 tasks completed

total: 1 test passed
```

I do not think it is user-friendly or obvious, one needs to pass the string with escaped spaces.

For our `testing-farm` cli this works well:

```
❯ testing-farm-redhat request --git-url https://gitlab.com/testing-farm/tests --plan /testing-farm/sanity -s SECRET=some-secret -e SCRIPT='test $SECRET = some-secret'
```

But of course, that is just because the variables are passed in via yaml:

```
❯ curl https://artifacts.dev.testing-farm.io/d451e1bd-d5ac-4d16-acb1-e51c8b6df206/git-maingiiwke3z/tmt-environment-testing-farm-sanity.yaml
SCRIPT: test $SECRET = some-secret
```

**Comment by lukaszachy** [comment]
We have this even documented: https://tmt.readthedocs.io/en/stable/spec/plans.html#environment

"Make sure to quote properly values which include spaces"

**Comment by lukaszachy** [comment]
For `tmt run -e SECRET=some-secret -e SCRIPT='test $SECRET = some-secret'` the pdb shows that: 
```
-> tmt.utils.environment_to_dict(
(Pdb) l
2459 	            # Variables from 'environment' options (highest priority)
2460 	            self._environment_from_options.update(
2461 ->	                tmt.utils.environment_to_dict(
2462 	                    variables=self.opt('environment'), logger=self._logger))
(Pdb) p self.opt('environment')
('SECRET=some-secret', 'SCRIPT=test $SECRET = some-secret')
```
As you can see the single quotes are already removed - that is shell thing - it processed those when evaluating your 'tmt run' command line.

**Comment by lukaszachy** [comment]
If you were to execute the exact line in bash you would get 
```
$ SECRET=some-secret
$ SCRIPT=test $SECRET = some-secret
bash: some-secret: command not found

```

**Comment by thrix** [comment]
Sorry, I still find it confusing, and it will be not just me:

```
❯ podman run -it -e SECRET=some-secret -e SCRIPT='test $SECRET == some-secret' registry.fedoraproject.org/fedora:38
[root@3071e8b800ff /]# eval $SCRIPT; echo $?
0
[root@3071e8b800ff /]# echo $SCRIPT
test $SECRET == some-secret
```

Like with other tools widely used tools, obviously what I am trying to do is working as I would expect.

It is good that is documented, but seeing an error like this at first:

```
❯ tmt run -e SECRET=some-secret -e SCRIPT='test $SECRET = some-secret' plan --name /testing-farm/sanity
/var/tmp/tmt/run-042
Invalid variable specification '$SECRET'.
```

Can make people confused.

> As you can see the single quotes are already removed - that is shell thing - it processed those when evaluating your 'tmt run' command line.

Well, we parse it the way this works: 

```
tmt run --environment "X=1 Y=2"
```

So, I get where this is coming from, I would rather revisit that personally.
The above might be something maybe Ansible supports, but we are working here with shell environment variables, not some jinja like variables

**Comment by lukaszachy** [comment]
What do you propose? As a user you run command with bash however what `tmt` receives is not a valid variable definition (as bash want it).

Should we have our own variable definitions?

**Comment by thrix** [comment]
@lukaszachy what would make sense to me is make this working

```
tmt run -e SOMETHING="a b bc"
```

As it is working with `podman` and testing-farm CLI.

Remove this weird thing:

```
--environment "X=1 Y=2"
```

I, personally, find that not useful or obvious it would work in command line tools.

**Comment by thrix** [comment]
@happz @psss WDYT?

**Comment by lukaszachy** [comment]
Compatibility with other tools as podman seems good to have. +1 to stop accepting  `--environment "X=1 Y=2"` and tread everything after first `=` as value for the variable.

**Comment by happz** [comment]
Might be a potentially breaking change for users, BTW. It does sound better to me, though, defining variables one by one, easier to parse, similar to `--context`, and so on.

**Comment by pcahyna** [comment]
There are basically two options here, with two suboptions for the second one:

1. treat the argument as a simple `<NAME>=<VALUE>` pair
2. do some parsing of of the argument
 a. implement the parsing yourself
 b. pass the value to the shell

I am in favor of 1. Parsing rules introduced in 2a. need to be implemented, and especially documented. Escaping will be needed (as this issue shows), making it complex to the users. IMO it is usually better to leverage the structure that is already provided (YAML lists in case of YAML, command line arguments in case of command line) if possible, rather than adding another layer of structure. I.e. why to support `--environment X=1 Y=2` when `--environment X=1 --environment Y=2` does the job fine?

In case of 2b., it will be possible to embed shell commands, leading to possibly unexpected behavior and misuse of the whole functionality.

The problem is, the current documentation very clearly indicates that option 2. has been chosen (esp. with the `X=1 Y=2` syntax). Note that it does not document the syntax, it only provides some examples and a comment that says "Make sure to quote properly values which include spaces" without specifying what the rules for "proper quoting" are. One can only guess that option 2b. (passing the stuff directly to shell) was probably chosen and thus the quoting syntax is the same as in shell - but this does not match the `pdb` output, which indicates that tmt parses the value itself.

As said above "Might be a potentially breaking change for users", so I think the correct way, if option 1. is preferred, is to introduce another option (`--parameter` maybe?) and let `--environment` silently die.

**Comment by thrix** [comment]
ok, so I am proposing for tmt 2.0, where breaking changes are possible

**Comment by lukaszachy** [comment]
We've done few breaking changes in 1.x already, this could be another one. Let's discuss on hacking session.

**Comment by psss** [comment]
Documented, @thrix is ok with the current status.
