### ISSUE TITLE
Include link to the `data` directory in the `html` report

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#2108]
When user runs `tmt-file-submit` as part of the test, it can be assumed the submitted file(s) will be accessible in the report. If they open a html report, only output.txt is being present as a log file, unless "custom results" is being used.

Not exactly related, but [in docs - Plans](https://tmt.readthedocs.io/en/devel/spec/plans.html#finish), there is this example:
```
finish:
    how: shell
    script: upload-logs.sh
```
I'm curious about what would the theoretical upload-logs script be actually doing, what would be the use-case.

**Comment by martinhoyer** [comment]
Also semi-related: Wouldn't it make sense to add `-r` switch to the tmt-file-submit's `cp` command, or is the $TMT_TEST_DATA dir supposed to only contain individual files and users are expected to create an archive/submit files one-by-one, if they want to submit contents of a directory?

**Comment by lukaszachy** [comment]
> Probably not a great example. The idea was something like "at the end of the plan rsync results to my custom host" or something like that. We should probably provide something more instructive / tangibly useful.

Maybe example how to save dmesg/journal...

**Comment by lukaszachy** [comment]
We had little chat about this issue here and two ways came to mind:
a) Have link to the 'data' (TMT_TEST_DATA) directory available in the html report. So one can get to that directory via link there however list of its content will not be provided (read: tmt will not care about what is inside).
We could add the name of the TMT_TEST_DATA to the result. Currently it's not there as it is part of paths provided in 'log' attribute. 

b) Create new attribute in the result (e.g. called artefact) which be a list of all files the test has submitted.

@martinhoyer Will "a)" be enough for your use case?

**Comment by martinhoyer** [comment]
> @martinhoyer Will "a)" be enough for your use case?

I think so, yes. Thanks for looking into it!

**Comment by psss** [comment]
This one should be easy, let's try to fit this into 1.25.

**Comment by psss** [comment]
> > @martinhoyer Will "a)" be enough for your use case?
> 
> I think so, yes. Thanks for looking into it!

Ok, good, I'll update the description accordingly.

**Comment by psss** [comment]
@bajertom is intersted in implementing this. In order to get the right path to the html template I think it would be best to extend the `Result` class with a `data` key which would store path to the test data directory:

https://github.com/teemtee/tmt/blob/38664d87b66f35ecc12971016a8f9a18194bc369/tmt/result.py#L80-L101

@happz, @lukaszachy, do you think this would be the right approach?

**Comment by happz** [comment]
> @bajertom is intersted in implementing this. In order to get the right path to the html template I think it would be best to extend the `Result` class with a `data` key which would store path to the test data directory:
> 
> https://github.com/teemtee/tmt/blob/38664d87b66f35ecc12971016a8f9a18194bc369/tmt/result.py#L80-L101
> 
> @happz, @lukaszachy, do you think this would be the right approach?

+1 for adding a path to test data directory link to `Result` objects, -1 on calling it `data` :) `execute` step calls it a "test data path", there's `ExecutePlugin.data_path()` method, I'd stick to `data_path`. `go()` can pass it to `Result.from_test()`, IIUIC, the `base.Test` instance is not enough to construct it.

**Comment by psss** [comment]
> I'd stick to `data_path`

Ack, sounds better.

**Comment by thrix** [comment]
moved to 1.28, seems @bajertom is OOTO, and no MR yet created
