### ISSUE TITLE
SSH connection terminated prematurely and output lost, error in tmt-run.log

### ISSUE THREAD

**Issue by vhumpa** [teemtee/tmt#2626]
This may relate to this previous issue https://github.com/teemtee/tmt/issues/2381 however circumstances are a bit different and @thrix  was asked to create a new one. 

Using the newly added [tty: true](https://gitlab.cee.redhat.com/desktopqe/gnome-system-monitor/-/blob/devel/el9/main.fmf?ref_type=heads#L44) to tackle the previously mentioned issue, the tests still end up in error state. See http://artifacts.osci.redhat.com/testing-farm/5787cc18-76cf-43c3-b2d7-3e0cc3b90265/ . The difference is that the output gets a bit further in particular the output of the headless command (runs under sudo and executes the tests under gdm spawned enviroment) is there but the connection terminates right aftwards. Was about to investigate timing, as previously times in the log suggested that the test actually finished, but only the output was missing. But discovered this error in tmt run log: http://artifacts.osci.redhat.com/testing-farm/5787cc18-76cf-43c3-b2d7-3e0cc3b90265/work-planl4_ixsz4/tmt-run.log 

Funny enough there are two tests that keep passing (consistently just these two) without any good reason why, because there is not any difference with these tests on the [runtest.sh](https://gitlab.cee.redhat.com/desktopqe/gnome-system-monitor/-/blob/devel/el9/runtest.sh?ref_type=heads) level. These are the same tests that kept passing even before with the issue https://github.com/teemtee/tmt/issues/2381, which makes me worry there is still some unresolved connection to that, but perhaps not.

**Comment by thrix** [comment]
I will look at it, any ideas what could be causing it are welcome.

**Comment by vhumpa** [comment]
Looks like this could be a non issue as @happz has kindly sourced this to the test(qecore library) actually killing the tmt's SSH bash by accident at the end of the test (the qecore-headless call)! I will do some diffing to confirm this, and if so, will close this issue.

**Comment by modehnal** [comment]
We are running a test build to confirm but as of now it seems like an issue on qecore side.

The issue comes from the `pgrep` which identified the TMT execution line as a process to be killed.

The way we are killing the processes is quite simple but effective. We need to kill everything with the name of the component we are testing as a cleanup to prevent any leftovers to be in a way of the next test.

We have a list of exceptions to prevent this cleanup to kill our main processes, which will have the name of the component in the process name. This list is effective for our current CI but with introduction of TMT the new exception needs to be added. Which I believe will solve the issue.

**Comment by vhumpa** [comment]
Yeah, so we confirmed that the SSH connection got indeed killed by us. Works now! http://artifacts.osci.redhat.com/testing-farm/27ffda70-7527-4157-b53e-d395b09d6273/  There is still question of the error in tmt-run.log which appears to be unrelated: http://artifacts.osci.redhat.com/testing-farm/27ffda70-7527-4157-b53e-d395b09d6273/work-plan36dj8cz6/tmt-run.log @thrix  do you want to keep this issue to investigate that (the "sleep" stuff) or can I close this one? Thanks!

**Comment by thrix** [comment]
Closing as  not an issue.
