### ISSUE TITLE
Test iteration identifier available as an environment variable

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2632]
For the purpose of syncing hosts in multi-host test scenario we need a unique test iteration identifier shared across hosts.
Such an identifier should be changed whenever a new test execution (even the same test) is done.
ATM, I am working with a combination of `TMT_TREE` (identifying run) and `TMT_TEST_SERIAL_NUMBER` (test number within a plan) but the problem is that such an identifier is very log and contains `/` characters. Therefore additional postprocessing is necessary in order to make it more usable.

See e.g.
https://github.com/RedHat-SP-Security/keylime-tests/commit/417eee23278474d1002efb2f4f5af8ca942c097b

**Comment by happz** [comment]
Concerning using a `start_time` timestamp for this purpose, my worry is about exposing different values to test invocations on different guests. A test `/foo` with `where: [server, client]` - `/foo` @ `server` would be given a different timestamp than `/foo` @ `client`. Each invocation is managed by a distinct thread, needs to do some preparation work, push this and pull that, and there is no guarantee that `start_time` would be the same for both invocations. In this sense, it feels like being too unique, not really better than a random string of characters, because no other object in this or future `tmt run` calls would see the same value.

My two cents, following the intent described above, attaching a unique tag to `tmt run` & exposing it to tests seems much easier to implement and reason about. tmt might even join this tag & test serial and expose them in a single variable if there's a good name for this union, to make it easier to use in scripts.

**Comment by kkaarreell** [comment]
I see. I didn't realize that each thread runs whole plan (or maybe discover) and `tmt` doesn't use thread per test. In that case your proposal with timestamp for run invocation (or any other identifier) makes sense and would be truly easier to implement.

**Comment by happz** [comment]
> I see. I didn't realize that each thread runs whole plan (or maybe discover) and `tmt` doesn't use thread per test.

Yes, for each `discover` phase, one thread is spawned for each of its guests (`where`). Threads are started at the same moment, but that's the only boundary they share, there is no synchronization done by tmt on the test level.

**Comment by psss** [comment]
Ack, a unique run identifier together with test serial number sounds reasonable. Let's try implement in the next release?
