### ISSUE TITLE
ReST rendering for CLI forced CRB dependency

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2690]
As reported by @martinhoyer, "after the introduction of "Simple ReST renderer for CLI help texts", tmt now relies on CRB repos on c9s and el9. Just checking this was evaluated/expected, as prior it was just EPEL"

```
# dnf install tmt-all --enablerepo=* |grep -i crb
 python3-docutils       noarch  0.16-6.el9         crb        1.6 M
 python3-pygments       noarch  2.7.4-4.el9        crb        2.0 M
```

The solution would be making these packages optional requirements, and provide dummy stand-ins to allow tmt work correctly without them.

**Comment by psss** [comment]
For the record, the `crb` repository was needed before (at some point) as well, see the [installation](https://tmt.readthedocs.io/en/stable/overview.html#install) instructions.

**Comment by happz** [comment]
I would be perfectly fine with keeping it as it is - my impression was CRB was introduced by my change, and it's not supposed to be there, hence the issue. But if it's acceptable, I'd be perfectly happy not doing anything :)

**Comment by martinhoyer** [comment]
> For the record, the crb repository was needed before (at some point) as well, see the [installation](https://tmt.readthedocs.io/en/stable/overview.html#install) instructions.

Indeed, apparently crb was required for ruamel-yaml packages, up until el-9.3. On CentOS Stream 9, there is an updated ruamel-yaml.clib and both packages are now in AppStream repos. Since this is recent change, the docutils and pygments have not introduced dependency on CRB, it does look like a non-issue. 

If tmt ever wants to get rid of CRB and be EPEL-only, there is a way :)

**Comment by martinhoyer** [comment]
Somehow I missed [crb is a requirement for EPEL](https://docs.fedoraproject.org/en-US/epel/#_el9). Sorry for the noise.
