### ISSUE TITLE
HTML report has a useless `data` column

### ISSUE THREAD

**Issue by comps** [teemtee/tmt#2856]
This got introduced somewhere between TMT version 1.29 and 1.31.1,
![image](https://github.com/teemtee/tmt/assets/1620988/7428f2a3-50f0-423b-aded-a8c4178d77f7)
however all the hyperlinks seem to lead to non-existent locations, returning 404: `https://server/path_to_tmt_datadir/plans/default/execute/None`.

I'm assuming the field was added as part of some feature, and the submitter didn't expect it to be `None` (unused).

**Comment by happz** [comment]
Can you share more details? Command line, for example, because it seems to work for me:

```
# added `exit 79` into tests/core/enabled/test.sh, the run:
$ tmt -c trigger=commit -vv run -a provision -h local report -h html plan -n '^/plans/features/core$' test -n '^/tests/core/enabled$'
```

I get a nice report, with an `error`, and its `data` leads to an existing directory:

![2024-04-12_16-40](https://github.com/teemtee/tmt/assets/116509/f349e524-6f7c-4b09-8965-569b0035aaaf)
![2024-04-12_16-40_1](https://github.com/teemtee/tmt/assets/116509/9ed715e2-56a6-4bcf-8f2a-c934fcd6d434)

**Comment by lukaszachy** [comment]
isn't that from 'result:custom'? we have a bug of not setting data dir when processing custom results

**Comment by comps** [comment]
> isn't that from 'result:custom'? we have a bug of not setting data dir when processing custom results
> 
> #2770

That's probably it, thanks, closing this one as a duplicate of https://github.com/teemtee/tmt/issues/2770.
