### ISSUE TITLE
polarion import does not correctly parse Polarion:tags field.

### ISSUE THREAD

**Issue by sbertramrh** [teemtee/tmt#2969]
Polarion:tags field separates different tags with a semi-colon. When tmt imports this field it imports it as a single tag.

e.g.
TAG1;TAG2 in Polarion is placed in the main.fmf as is.
```
tag:
  -  TAG1;TAG2
```

But it should be:
```
tag:
  -  TAG1
  -  TAG2
```

**Comment by KwisatzHaderach** [comment]
That's the 'neat' part, it can be anything, tags field in Polarion is free text, so what tmt currently matches is space (as that is what is used by export), but since other tools can use anything else I can see some project having tags separated by ','.

Let's improve the matching a bit and use also ',' and ';' as separators and hope for no problems with that.
