### ISSUE TITLE
execute method beakerlib{,.tmt}, shell{,.tmt} does not capture console output chronologically

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#390]
It looks like _stdout_ and _stderr_ are not in sync as it normally would on console. See /var/tmp/tmt/run-066/plans/default/execute/logs/sudo/Sanity/default-sudo-config-files/out.log and /var/tmp/tmt/run-066/plans/default/execute/logs/sudo/Sanity/default-sudo-config-files/journal.txt in the linked archive. Note mainly the Setup phase ending position in the out.log.

I think this qualifies as quite big UX issue.

I expect the solution might be to run the test with both outputs redirected to just one. I do not know how is this handled form python, though.

[run.tar.gz](https://github.com/psss/tmt/files/5330062/run.tar.gz)

**Comment by pvalena** [comment]
> It looks like _stdout_ and _stderr_ are not in sync as it normally would on console. See /var/tmp/tmt/run-066/plans/default/execute/logs/sudo/Sanity/default-sudo-config-files/out.log and /var/tmp/tmt/run-066/plans/default/execute/logs/sudo/Sanity/default-sudo-config-files/journal.txt in the linked archive. Note mainly the Setup phase ending position in the out.log.
> 
> I think this qualifies as quite big UX issue.
> 
> I expect the solution might be to run the test with both outputs redirected to just one. I do not know how is this handled form python, though.
> 
> [run.tar.gz](https://github.com/psss/tmt/files/5330062/run.tar.gz)

IMHO, from my experience this can happen on any level, in any language. It just happens very rarely. `stderr` and `stdout` are two different outputs, by design, and should be treated as such, I'm not sure how to mitigate this in python (so it doesn't happen very often) but joining the outputs shouldn't be the solution, as we need to capture and parse those outputs separately.

**Comment by thrix** [comment]
it would be maybe better to capture them in two different files ... instead of having them merged in such a weird way

**Comment by sopos** [comment]
> it would be maybe better to capture them in two different files ... instead of having them merged in such a weird way

This would produce even less useful output. In case of beakerlib, all the beakerlib messages (:: [ ...) are printed to _stderr_, while the majority of the commands outputs (_rlRun_ command) is printed to _stdout_. In case of `rlRun "echo test"` we really want to have it serialized chronologically to benefit from the output being marked at the beginig and at the end so it is obvious where the echo output starts and ends.
If this happens too often (in my reported case always) it is a deal breaker as the logs are useless from debugging POV. We really need the output being the same as _Restraint_ is able to produce - chronologically.

**Comment by sopos** [comment]
> IMHO, from my experience this can happen on any level, in any language. It just happens very rarely. `stderr` and `stdout` are two different outputs, by design, and should be treated as such, I'm not sure how to mitigate this in python (so it doesn't happen very often) but joining the outputs shouldn't be the solution, as we need to capture and parse those outputs separately.

What's the actual reason for parsing it separately? In case of beakerlib I cannot imagine what you would like to gather, there are more reliable ways to get data - _TestResults_ file or _journal.xml_ or _journal.meta_ possibly.

**Comment by pvalena** [comment]
> What's the actual reason for parsing it separately? In case of beakerlib I cannot imagine what you would like to gather, there are more reliable ways to get data - _TestResults_ file or _journal.xml_ or _journal.meta_ possibly.

It's not that we tell the script to **do it** (but the opposite instead, if I'm reading the code correctly). It's rather the implementation of `execution` by itself. When you take some command (the `test` in this case), and `execute` it remotely, you get two outputs.

The two executors we have in TMT behave differently:

   1. In your case, the default [tmt executor](https://github.com/psss/tmt/blob/4005972fb60d9418d4f13f5f4fe55e8a09a0929d/tmt/steps/execute/internal.py#L75) is used, where the test is run with `join=True`.
   The actual implementation of the provisioner execute (a general remote execution) method, relies on the `run()` method in `utils.py`, which reads both `stderr` and `stdout`, and tries to output them as they come (the details may have changed since last time I've checked). This is done to be able to output every line immediately, while logging it at the same time. Maybe it can be enhanced in some way, but in general, you need those outputs separate.

  2. The [detach executor](https://github.com/psss/tmt/blob/4005972fb60d9418d4f13f5f4fe55e8a09a0929d/tmt/steps/execute/detach.py#L119) should not suffer from this, but it's also not able to output the test result _interactively_ (it waits for the test suite to finish).
  It uses a [shell script](https://github.com/psss/tmt/blob/4005972fb60d9418d4f13f5f4fe55e8a09a0929d/tmt/steps/execute/run.sh#L168) to run all tests remotely (detached from host), at once. With this execution, the `stderr` output from the test is joined directly (`2>&1`) with the actual execution of the test, as it would be on the console/terminal output, and logged. All the logs are afterwards transfered and [processed](https://github.com/psss/tmt/blob/4005972fb60d9418d4f13f5f4fe55e8a09a0929d/tmt/steps/execute/detach.py#L127). (The `detach` executor could be extended to provide more _interactive_ functionality as well, but that would go against the design.)

HIH.

**Comment by sopos** [comment]
I'm not an expert in python so I do not know how the command execution is done for `join=True`. However you're right that _beakerlib.detach_ serializes the output correctly. However for _bakerlib.tmt_ I can force the output to be joined in the test using `exec 1>&2` or `exec 2>&1`. Both do their job. So it would be good to be able to do the same on the tmt side so the tests does not need to be modified.

I also tried to put there a `sleep 5` at the end of the test as @psss suggested me but that did not help.

So for now the detach executor is the only one which really produces the output to be usable to debug test issues without any workarounds.

**Comment by psss** [comment]
From user perspective we definitely need to have `stdout` and `stderr` joined in order to be able to efficiently review test logs. There was an attempt in `standard-test-roles` to separate output into two files and then there was very [negative feedback](https://pagure.io/fedora-ci/general/issue/57) from users.

Regarding the implementation: As Pavel mentioned, the internal executor uses `join` so the two outputs are put together by `subprocess.Popen()`. I would expect that code should be able to handle this properly. If not we will have to find a better solution.

@sopos, does it happen always with that test? Have you seen in in other tests?

**Comment by sopos** [comment]
It happens to be consistently for that simple test. I'm not sure how other tests as I did not do any real testing with tmt just yet so I did not pay much attention to this in particular.

**Comment by psss** [comment]
Interesting, I tried to run that test and the log seems to be in a correct order.

**Comment by sopos** [comment]
I used `tmt run -vvvddd -a provision -h connect -g 10.0.139.163 prepare -h shell -s 'dnf config-manager --enable beaker-tasks' execute -h beakerlib.tmt tests --name .` where the IP belonged to a rhel-8.3 1MT machine.

**Comment by pvalena** [comment]
@sopos, IMHO the remote host / jitter plays a role in this. That's a setup where `detach` executor's use is aimed. Can you confirm for us that using `detach` executor mitigates the issue?

**Comment by sopos** [comment]
I confirmed it alredy in https://github.com/psss/tmt/issues/390#issuecomment-704546528

**Comment by pvalena** [comment]
> I confirmed it alredy in [#390 (comment)](https://github.com/psss/tmt/issues/390#issuecomment-704546528)

Sorry, I've missed that comment.

> `exec 1>&2` or `exec 2>&1`

This is kind-of a hack, but as the test does not produce any important stderr vs stdout for us to deal with (it's joined upon recieving), so it shouln't matter. Could we maybe add it to the execution for `join=True`? It requires `shell=True`, but that's on anyway, right?

Something like:
```python
def execute(...
    if join:
        run(command + ' 2>&1', ....)   # the one from utils.py
```
(not an actual code)

 Or, optionally we could change this in utils.py:

```python
def run( ...
    if join and shell:
        command = command + ' 2>&1'
```

Just few notes, from actuall shell POV:

`something 2>&1` does actually redirect stderr to where `1` is pointing at the moment (so it could be a file, or anything). AFAIR it also ignores/invalidates all previous `2>anything` (on the same command line).

Therefore, we need to keep in mind:
1. It should be always in the end of shell command.
2. User can't manualy redirect `stderr` from the command. (It'd have to be redirected in the script itself, with `exec 2>...` f.e..)

**Comment by lukaszachy** [comment]
@sopos Is this still a problem?

**Comment by sopos** [comment]
Not sure, probably not. It was a corner case, anyway. I did not notice it since than.
