### ISSUE TITLE
tmt run eats space, explore ways how to limit disk usage

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#645]
All `tmt run` data including test cloud images are kept on the disk after run is finished.
This can take a lot of space.

Ideas (from the workshop)
- Remove run data unless specified otherwise
- Keep only failed runs
- Delete unnecessary data (e.g. tests from discover step) and keep only logs

**Comment by FrNecas** [comment]
#436 should partially help so that it is not necessary to clean `/var/tmp/tmt` manually

**Comment by lukaszachy** [comment]
Also - since default workdir is in `/var/tmp` tmt could set rules for `systemd-tmpfiles` so this dir will be cleaned regularly

**Comment by FrNecas** [comment]
Out of these suggestions, I feel like removing successful runs (keeping failed runs) is the most non-invasive, it doesn't really affect the user experience. Especially if we do the removal in finish step since that means that if finish is for some reason skipped (e.g. debugging scenario - running `tmt run discover provision prepare execute report`) then the run is kept and the execute can be rerun or login can be used etc. I will implement this, should be simple.

**Comment by psss** [comment]
Seems like the workdir pruning covered the essential part of the use case. Closing, feel free to reopen if still important.
