### ISSUE TITLE
Implement a user configuration

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#84]
Seems we'll soon need a way how to store user configuration data. For example `tmt test export --nitrate` might need a `url` to the test case management system.

Brainstorming first ideas here: What about storing data under `$HOME/.config/tmt` in the form of an `fmf` tree? For the above-mentioned example we could have something like this:

    /test/convert/nitrate:
        url: https://nitrate.example.com/

This would work naturaly / consistently with how the rest of data is handled in `tmt`.

**Comment by psss** [comment]
Config story has been already [described](https://tmt.readthedocs.io/en/latest/stories/cli.html#config).

**Comment by psss** [comment]
Proposing for 2.0 as discussed on today's hacking session.

**Comment by psss** [comment]
This is blocking #813.

**Comment by RHEmployee** [comment]
Is this still free? It can be nice to play around and try to implement:
https://github.com/psss/tmt/issues/38

**Comment by psss** [comment]
Yes, this is free. I expect the configuration format will need some discussion though.

**Comment by psss** [comment]
@therazix, regarding the implementation I would recommend to start with simplifying the following code:

https://github.com/teemtee/tmt/blob/e485608afcbe369fb67834a13a33aa174f63ac1c/tmt/utils/jira.py#L85-L124

Instead of the complex checking of the types and values, the code above should probably just do something like:

    issue_trackers = tmt.utils.Config().get("/link/issue-trackers")

or maybe even something like this?

    issue_trackers = tmt.utils.Config().link.issue-trackers

The rest would be handled by the `Config` class. @happz might also have some hints about how the implementation could look like.

**Comment by LecrisUT** [comment]
If I read this correctly the goal is for the user configurations to override the contents of the fmf file effectively? There is an ambiguity of how to order the preference between:
- default value (no field in the project's fmf)
- user config fmf
- project's fmf field specified

Maybe if we put some more restrictions that the user config can only affect leaf configurations the intent could be clearer. But then it can get quite weird figuring out which user config applies to the fmf tree of which project. Or are the fmf fields defined in the user configuration completely orthogonal, in which case what would the path signify? Are only a few fields or containers meant to be linked with configurations, maybe the class definition can be changed to a decorator instead of inheritance?

About the container part, it would depend on the part above, but generally I was thinking that the containers are just the datastructures and basically as close to a json-schema as possible. The reading of the source: fmf tree, click arguments or configuration could be completely separate from this. How to unify the definitions within the `field` would be a bit more tricky because that one is getting quite dense in the amount of arguments that are being passed, if only you could decorate those :face_exhaling:. Well there is a way I guess that attrs is using by wrapping dummy functions [^1], but that would get verbose quite quickly.

[^1]: https://www.attrs.org/en/stable/examples.html#defaults

**Comment by psss** [comment]
> If I read this correctly the goal is for the user configurations to override the contents of the fmf file effectively? There is an ambiguity of how to order the preference between...

I see, the original [story](https://tmt.readthedocs.io/en/latest/stories/cli.html#config) describing/brainstorming the possible features can be confusing. I think we would like to start small first. Without handling user versus system configuration and without interaction with test or plan metadata.

We have the following tangible use case for the `tmt link` command: An `fmf` node `/link` saved under the `~/.config/tmt` tree intended for storing supported issue trackers. The config can look like this:

```yaml
issue-tracker:
  - type: jira
    url: https://issues.redhat.com
    tmt-web-url: http://tmt.testing-farm.io/
    token: <secret>
```

This is in no way related to affecting default values of tests or plans. It's a config to be used solely by the `tmt link` command. So, as the first step, here we would like to validate that it has the expected format and store the values in easily accessible objects.
